# Generated by Django 2.1.6 on 2019-02-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmanagement', '0003_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
