# Generated by Django 2.1.6 on 2019-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmanagement', '0011_auto_20190215_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
