# Generated by Django 2.1.6 on 2019-02-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogmanagement', '0012_auto_20190218_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
