# Generated by Django 2.1.6 on 2019-02-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmanagement', '0016_auto_20190218_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
    ]
